# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('686a9c39-73ae-4c29-b79f-5430db3265c7'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อ')),
                ('on_date', models.DateField(verbose_name='วันที่')),
                ('on_time', models.TimeField(verbose_name='เวลา')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการเกิดอุบัติเหตุ',
                'db_table': 'tbt_accidents',
            },
        ),
        migrations.CreateModel(
            name='AccidentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e9d9d059-1a71-4c92-8fce-5cdfa8fc5ab2'), editable=False, primary_key=True, serialize=False)),
                ('accident_type', models.CharField(choices=[('C', 'Corrective'), ('D', 'Defective')], max_length=1, verbose_name='ประภท')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลประเภทอุบัติเหตุ',
                'db_table': 'tbt_accidentgroups',
            },
        ),
        migrations.CreateModel(
            name='ImagesAccident',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3bb54fe9-2225-4e2c-be97-7a8669cd7656'), editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='', verbose_name='รูป/เอกสารประกอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accident', verbose_name='หัวข้อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรูปภาพประกอบการเกิดอุบัติเหตุ',
                'db_table': 'tbt_imageaccidents',
            },
        ),
        migrations.CreateModel(
            name='ApproveAccident',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3fb052de-9525-460c-b64d-b76f12be4f49'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='แนวทางแก้/ข้อเสนอแนะ')),
                ('is_approve', models.BooleanField(blank=True, choices=[(False, '-'), (True, 'รับทราบ')], default=False, null=True, verbose_name='รับทราบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accident.accident', verbose_name='หัวข้ออุบัติเหติ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรับทราบเรื่องอุบัติเหตุ',
                'db_table': 'tbt_approveaccidents',
            },
        ),
    ]
