# Generated by Django 4.0 on 2021-12-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accident', '0002_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='whs_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.whs', verbose_name='พื้นที่เกิดอุบัติเหตุ'),
        ),
    ]
