# Generated by Django 4.0 on 2021-12-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('regional', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.educationals', verbose_name='ระดับการศึกษา'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.position', verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='profile',
            name='section_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.section', verbose_name='สาขา/หน่วยงาน'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shift_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.shift', verbose_name='ข้อมูลเข้างาน'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regional.zipcode', verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='permision',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.profile', verbose_name='ผู้ใช้งาน'),
        ),
    ]
