# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('91a8b802-1551-4cf6-b3cf-5aee12fbd47b'), editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('from_datetime', models.DateTimeField(verbose_name='วันที่เริ่ม')),
                ('to_datetime', models.DateTimeField(verbose_name='สิ้นสุดที่')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('is_holiday', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, editable=False, verbose_name='วันหยุดตามปฎิทินของบริษัท')),
                ('leader_approve', models.IntegerField(blank=True, choices=[(0, '-'), (1, 'Reject'), (2, 'Approved')], null=True, verbose_name='หัวหน้างาน/สถานะ')),
                ('leader_approve_at', models.DateField(blank=True, null=True, verbose_name='หัวหน้า/อัพเดทข้อมูลเมื่อ')),
                ('leader_comment', models.TextField(blank=True, null=True, verbose_name='หัวหน้า/ข้อมูลเพิ่มเติม')),
                ('mgr_approve', models.IntegerField(blank=True, choices=[(0, '-'), (1, 'Reject'), (2, 'Approved')], null=True, verbose_name=' ผู้จัดการ/สถานะ')),
                ('mgr_approve_at', models.DateField(blank=True, null=True, verbose_name='ผู้จัดการ/อัพเดทข้อมูลเมื่อ')),
                ('mgr_comment', models.TextField(blank=True, null=True, verbose_name='ผู้จัดการ/ข้อมูลเพิ่มเติม')),
                ('hr_approve', models.IntegerField(blank=True, choices=[(0, '-'), (1, 'Reject'), (2, 'Approved')], null=True, verbose_name='พนักงานทัพยากรบุคคล/สถานะ')),
                ('hr_approve_at', models.DateField(blank=True, null=True, verbose_name='พนักงานทัพยากรบุคคล/อัพเดทข้อมูลเมื่อ')),
                ('hr_comment', models.TextField(blank=True, null=True, verbose_name='พนักงานทัพยากรบุคคล/ข้อมูลเพิ่มเติม')),
                ('sendmail', models.BooleanField(choices=[(False, 'ยังไม่ส่ง'), (True, 'ส่งแล้ว')], default=False, verbose_name='สถานะการส่งเมล์')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.profile', verbose_name='ชื่อพนักงาน')),
            ],
            options={
                'verbose_name_plural': 'บันทึกข้อมูลทำงานล่วงเวลา',
                'db_table': 'tbt_overtimes',
            },
        ),
    ]
