# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f1852f1e-5e7a-4a02-970a-82b9b5fc7c60'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('total_like', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ชอบ')),
                ('total_dislike', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ไม่ชอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('comment_by', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.profile', verbose_name='แสดงความคิดเห็นโดย')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแสดงความคิดเห็น',
                'db_table': 'tbt_comments',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f20a59e2-4d7c-40d1-af52-c78753d17359'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('total_like', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ชอบ')),
                ('total_dislike', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ไม่ชอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webboard.comment', verbose_name='หัวข้อ/เรื่อง')),
                ('reply_by', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.profile', verbose_name='ตอบกลับโดย')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลตอบกลับความคิดเห็น',
                'db_table': 'tbt_replys',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('157f6353-5ebd-48b8-b40b-8fca2285ea57'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ/เรื่อง')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('total_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนผู้อ่าน')),
                ('total_like', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ชอบ')),
                ('total_dislike', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนที่ไม่ชอบ')),
                ('published_at', models.DateField(verbose_name='วันที่ประกาศ')),
                ('published', models.BooleanField(blank=True, choices=[(False, 'ร่าง'), (True, 'เผยแพร่')], default=False, null=True, verbose_name='เผยแพร่')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.categories', verbose_name='หมวดหมู่')),
                ('created_by', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.profile', verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลประชาสัมพันธ์',
                'db_table': 'tbt_webboards',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webboard.post', verbose_name='หัวข้อ/เรื่อง'),
        ),
    ]
