# Generated by Django 4.0 on 2021-12-08 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('34164868-3b39-4761-82a3-c3bb3c4d34ef'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลหมวดหมู่ข่าวสาร',
                'db_table': 'tbt_categories',
            },
        ),
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('489714ec-8da8-47c6-b6b0-dae5f7a53c18'), editable=False, primary_key=True, serialize=False)),
                ('on_date', models.DateField(verbose_name='วันที่')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลปฏิทินวันหยุดของบริษัท',
                'db_table': 'tbt_companycalendars',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('dab62701-6a1f-44cb-b7bc-7b12b3812ac7'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแผนก',
                'db_table': 'tbt_departments',
            },
        ),
        migrations.CreateModel(
            name='Educationals',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7c0c8dea-5839-4ea3-a11a-f603fc2dfe81'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลระดับการศึกษา',
                'db_table': 'tbt_educationals',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('42386a59-a803-4476-8bb9-1d9719e480c8'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลประเภทการลา',
                'db_table': 'tbt_leavegroups',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ed524689-5bf7-4c6c-a7d7-9570dc6f251d'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('approve_leave', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติการลา')),
                ('approve_overtime', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติล่วงเวลา')),
                ('approve_accident', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติ/แสดงความคิดเห็นการเกิดอุบัติเหตุ')),
                ('is_assessor', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='สามารถประเมินพนักงานได้')),
                ('mail_to', models.CharField(max_length=255, verbose_name='เมล์ TO')),
                ('mail_cc', models.CharField(max_length=255, verbose_name='เมล์ CC')),
                ('mail_bc', models.CharField(max_length=255, verbose_name='เมล์ BC')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลองค์กร',
                'db_table': 'tbt_organizations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e417e71a-4df7-4061-96a4-f2969ed10c3a'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลตำแหน่ง',
                'db_table': 'tbt_positions',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e2105a48-7614-42b9-91d0-eef6ccdd65dc'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลสาขา/หน่วยงาน',
                'db_table': 'tbt_sections',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('49fb499f-37a1-462d-a912-ee7393d923d0'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('time_attendance', models.DecimalField(decimal_places=18, default=8, max_digits=44, null=True, verbose_name='เวลาทำงาน(ชม.)')),
                ('fee_per', models.DecimalField(decimal_places=18, default=0, max_digits=44, null=True, verbose_name='ค่ากะ(บาท)')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการเข้างาน',
                'db_table': 'tbt_shiftments',
            },
        ),
        migrations.CreateModel(
            name='Whs',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7ea4a195-b9fa-4806-b296-62468f6f8d9b'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลคลังสินค้า',
                'db_table': 'tbt_whs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ed83aa04-33b7-4606-9503-5c22cf29dcd4'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('organize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.organization', verbose_name='ข้อมูลองค์กร')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.position', verbose_name='ตำแหน่ง')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรายละเอียดขององค์กร',
                'db_table': 'tbt_organizationdetails',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.position', verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
