# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('52cbdb80-e964-420e-a192-9a7736688d2d'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลหมวดหมู่ข่าวสาร',
                'db_table': 'tbt_categories',
            },
        ),
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('69d0f2d0-e62d-4717-b0c7-8c9dcc0c2bad'), editable=False, primary_key=True, serialize=False)),
                ('on_date', models.DateField(verbose_name='วันที่')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลปฏิทินวันหยุดของบริษัท',
                'db_table': 'tbt_companycalendars',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('04fae855-da53-4074-bc46-4443004f7790'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแผนก',
                'db_table': 'tbt_departments',
            },
        ),
        migrations.CreateModel(
            name='Educationals',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6ab9dbc6-7b64-4413-bbde-078e03a23577'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลระดับการศึกษา',
                'db_table': 'tbt_educationals',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6e430904-759d-40c5-87cc-dec85bf38b2e'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลประเภทการลา',
                'db_table': 'tbt_leavegroups',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0972159a-dea9-48e7-af17-a6ca4e1a1cbe'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('approve_leave', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติการลา')),
                ('approve_overtime', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติล่วงเวลา')),
                ('approve_accident', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='อนุมัติ/แสดงความคิดเห็นการเกิดอุบัติเหตุ')),
                ('is_assessor', models.BooleanField(blank=True, choices=[(False, 'ไม่'), (True, 'ใช่')], default=False, null=True, verbose_name='สามารถประเมินพนักงานได้')),
                ('mail_to', models.CharField(max_length=255, verbose_name='เมล์ TO')),
                ('mail_cc', models.CharField(max_length=255, verbose_name='เมล์ CC')),
                ('mail_bc', models.CharField(max_length=255, verbose_name='เมล์ BC')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='หัวข้อ/แผนก')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลองค์กร',
                'db_table': 'tbt_organizations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2f5800de-efd2-4dd5-ab8f-de014b5ecd6e'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลตำแหน่ง',
                'db_table': 'tbt_positions',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eb56e67e-08ad-43ba-a1fe-5344247ca231'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลสาขา/หน่วยงาน',
                'db_table': 'tbt_sections',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0135d30d-6529-4aab-8d0b-7d22ab04e1f2'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('time_attendance', models.DecimalField(decimal_places=18, default=8, max_digits=44, null=True, verbose_name='เวลาทำงาน(ชม.)')),
                ('fee_per', models.DecimalField(decimal_places=18, default=0, max_digits=44, null=True, verbose_name='ค่ากะ(บาท)')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการเข้างาน',
                'db_table': 'tbt_shiftments',
            },
        ),
        migrations.CreateModel(
            name='Whs',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('422a648c-3757-4bb5-a365-79f27202a0ca'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลคลังสินค้า',
                'db_table': 'tbt_whs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('72bebeca-8926-4c09-8548-46d2a28a619e'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('organize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.organization', verbose_name='ข้อมูลองค์กร')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.position', verbose_name='ตำแหน่ง')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรายละเอียดขององค์กร',
                'db_table': 'tbt_organizationdetails',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.position', verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
