# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fac74f2e-a96d-4394-b081-37c1f4b678a8'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อหมวดหมู่')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลหมวดหมู่',
                'db_table': 'tbt_activitiescategories',
            },
        ),
        migrations.CreateModel(
            name='ActivitiesChoise',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7faa30ea-89a2-45d4-a161-c7ded5442889'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ/เรื่อง')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('full_score', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=44, null=True, verbose_name='คะแนนเต็ม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลหัวข้อ/เรื่อง',
                'db_table': 'tbt_activitieschoies',
            },
        ),
        migrations.CreateModel(
            name='ActivitiesCleanup',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('16476395-3b73-4762-8da2-591675b44568'), editable=False, primary_key=True, serialize=False)),
                ('activities_date', models.DateField(verbose_name='วันที่ทำกิจกรรม')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('score', models.DecimalField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], decimal_places=18, default=0, max_digits=44, null=True, verbose_name='คะแนนที่ได้')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการทำกิจกรรม 5 ส',
                'db_table': 'tbt_activitiescleanups',
            },
        ),
        migrations.CreateModel(
            name='ImagesActivites',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e389d029-58e3-4dca-8e18-de036e0a2107'), editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='', verbose_name='รูปประกอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('squize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitiescleanup.activitiescleanup', verbose_name='หัวข้อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลเอกสารประกอบการทำกิจกรรม 5 ส',
                'db_table': 'tbt_imagesactivities',
            },
        ),
        migrations.CreateModel(
            name='ActivitiesForOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5de67536-247f-4e5f-b3e8-01aae2d6db90'), editable=False, primary_key=True, serialize=False)),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='รายละเอียด/ข้อมูลเพิ่มเติม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('activities_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitiescleanup.activitieschoise', verbose_name='หัวข้อ/เรื่อง')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลหัวข้อ/เรื่อง สำหรับแผนก',
                'db_table': 'tbt_activitiesorgans',
            },
        ),
    ]
