# Generated by Django 4.0 on 2021-12-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activitiescleanup', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesfororganization',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='หัวข้อ/แผนก'),
        ),
        migrations.AddField(
            model_name='activitiescleanup',
            name='activities_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitiescleanup.activitiesfororganization', verbose_name='หัวข้อ/เรื่อง'),
        ),
        migrations.AddField(
            model_name='activitieschoise',
            name='category_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitiescleanup.activitiescategories', verbose_name='หมวดหมู่'),
        ),
    ]
