# Generated by Django 4.0 on 2021-12-09 02:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTester',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('21c80729-282d-4a82-a97c-398ebcd59044'), editable=False, primary_key=True, serialize=False)),
                ('on_round', models.IntegerField(blank=True, default=1, null=True, verbose_name='รอบที่สอบ')),
                ('on_date', models.DateTimeField(verbose_name='วันที่ทดสอบ')),
                ('score', models.DecimalField(decimal_places=18, default=0, max_digits=44, null=True, verbose_name='คะแนนนที่ได้')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.profile', verbose_name='ผู้ทำการทดสอบ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลผลการทดสอบหลังการอบรม',
                'db_table': 'tbt_aftertrainings',
            },
        ),
        migrations.CreateModel(
            name='Squize',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6fc3e873-1b69-49b2-b26c-e36dfc675a1d'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด/เสนอแนะ')),
                ('score_length', models.DecimalField(decimal_places=18, max_digits=44, verbose_name='คะแนนเต็ม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแบบทดสอบหลังการอบรม',
                'db_table': 'tbt_squizes',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('140609a5-3adc-438b-8873-06d951cd5704'), editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255, unique=True, verbose_name='บริษัท')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='ที่อยู่อีเมล์')),
                ('telno', models.CharField(max_length=255, unique=True, verbose_name='เบอร์โทรศัพท์')),
                ('mobileno', models.CharField(max_length=255, unique=True, verbose_name='เบอร์โทรศัพท์มือถือ')),
                ('avatar', models.CharField(max_length=255, unique=True, verbose_name='รูปประจำตัว')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.position', verbose_name='ตำแหน่ง')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลวิทยากร',
                'db_table': 'tbt_trainers',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('61864452-c678-49fb-9d02-8c1a4a57c587'), editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='หัวข้อการอบรม')),
                ('on_date', models.DateField(verbose_name='วันที่อบรม')),
                ('from_time', models.TimeField(verbose_name='เวลา/เริ่ม')),
                ('to_time', models.TimeField(verbose_name='เวลา/ถึง')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('is_complete', models.BooleanField(blank=True, choices=[(False, 'ยัง'), (True, 'เรียบร้อย')], default=False, verbose_name='อบรมแล้ว')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลการอบรม',
                'db_table': 'tbt_trainings',
            },
        ),
        migrations.CreateModel(
            name='TrainingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('908cef7e-867d-49f9-9305-913ad5ed2022'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='หัวข้อ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('total_per_room', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนคน/ห้อง')),
                ('is_idle', models.BooleanField(blank=True, choices=[(False, 'ว่าง'), (True, 'ไม่ว่าง')], default=False, null=True, verbose_name='การใช้งาน')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลห้องอบรม',
                'db_table': 'tbt_trainingrooms',
            },
        ),
        migrations.CreateModel(
            name='TrainingDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00eae528-561b-440e-a238-396f6221befa'), editable=False, primary_key=True, serialize=False)),
                ('on_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ทำการอบรม')),
                ('training_score', models.DecimalField(blank=True, decimal_places=18, max_digits=44, verbose_name='คะแนนที่ได้')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด/เสนอแนะ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.profile', verbose_name='ชื่อพนักงาน')),
                ('training_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='หัวข้อมที่อบรม')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลพนักงานที่เข้าอบรม',
                'db_table': 'tbt_trainingdetail',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='room_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.trainingroom', verbose_name='ห้องที่อบรม'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.trainer', verbose_name='วิทยากร'),
        ),
        migrations.CreateModel(
            name='SquizeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bb338f32-0ed9-4a5e-8def-89e8f4830645'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='คำถาม')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('score_length', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=44, null=True, verbose_name='คะแนนเต็ม')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.squize', verbose_name='แบบทดสอบ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแบบทดสอบหลังการอบรม/ข้อสอบ',
                'db_table': 'tbt_squizedetails',
            },
        ),
        migrations.CreateModel(
            name='SquizeChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f61e5c7b-f150-4780-aa11-74893438ae53'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='คำตอบ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, verbose_name='รายละเอียด')),
                ('score_length', models.DecimalField(blank=True, decimal_places=18, default=0, max_digits=44, null=True, verbose_name='คะแนนเต็ม')),
                ('is_answer', models.BooleanField(choices=[(False, 'ไม่ถูก'), (True, 'ถูก')], default=False, verbose_name='เฉลย/คำตอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.squizedetail', verbose_name='คำถาม')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลแบบทดสอบหลังการอบรม/คำตอบ',
                'db_table': 'tbt_squizechoices',
            },
        ),
        migrations.AddField(
            model_name='squize',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='หัวข้ออบรม'),
        ),
        migrations.CreateModel(
            name='ImagesTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('69bc6be5-64b2-4087-b859-0db57cf5f22a'), editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='', verbose_name='รูปประกอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='หัวข้อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรูปภาพประกอบการอบรม',
                'db_table': 'tbt_imagetrainings',
            },
        ),
        migrations.CreateModel(
            name='ImagesSquize',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('232f6e70-107f-4778-8b4c-c1cebfb1c0f5'), editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='รูปประกอบ')),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('squize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.squize', verbose_name='หัวข้อ')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลรูปภาพประกอบการอบรม',
                'db_table': 'tbt_imagesquizes',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTesterDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7707c5de-ddc9-4f8a-bc07-7d8edb96bd25'), editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(choices=[(False, 'ปิด'), (True, 'เปิด')], default=False, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('answer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.squizechoice', verbose_name='คำตอบ')),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.employeetester', verbose_name='หัวข้อการอบรม')),
                ('squize_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.squizedetail', verbose_name='คำถาม')),
            ],
            options={
                'verbose_name_plural': 'ข้อมูลผลการทดสอบหลังการอบรม/คำตอบ',
                'db_table': 'tbt_aftertrainingdetails',
            },
        ),
        migrations.AddField(
            model_name='employeetester',
            name='training_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.training', verbose_name='หัวข้อการอบรม'),
        ),
    ]
